##############  Misc. Configuration    ##############

#    5am every day
purge.cron.expression=0 0 5 * * ?

# Uncomment the keys to enable captcha
#google.recaptcha.key.site=6LfaHiITAAAAAAgZBHl4ZUZAYk5RlOYTr6m2N34X
#google.recaptcha.key.secret=6LfaHiITAAAAANpDTA_Zflwib95IhDqg2SNRLt4U

#jwt.secret = pdtxF5zklRAKFIL8fKtv
#jwt.secret.admin = GoeAYrTVVB2tygCCzfdh
#jwt.secret.shopify_app = i5mHiaeeG5v3WxoKbu7X

jwt.secret = ${random.value}
jwt.secret.admin = ${random.value}
jwt.secret.shopify_app = ${random.value}

##############  Hikari Configuration    ##############

#db.driver=Connector/J
#com.mysql.jdbc.Drivers
db.driver=com.mysql.jdbc.Driver
#com.mysql.jdbc.jdbc2.optional.MysqlDataSource
#db.url=jdbc:mysql://localhost:3306/test2?useLegacyDatetimeCode=false
#db.url=jdbc:mysql://localhost:3306/test2?serverTimezone=UTC
db.url=jdbc:mysql://${MYSQL_DB_HOSTNAME}:${MYSQL_DB_PORT}/${MYSQL_DB}?serverTimezone=UTC
db.username=${MYSQL_USER}
db.password=${MYSQL_PASSWORD}

#db2.url=jdbc:mysql://localhost:27017/test2
#db2.username=oxi
#db2.password=feisthmiki#10


##############  Hibernate Configuration ##############

hibernate.connection.zeroDateTimeBehavior=convertToNull
#Configures the used database dialect. This allows Hibernate to create SQL
#that is optimized for the used database.
hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
#Specifies the action that is invoked to the database when the Hibernate
#SessionFactory is created or closed.
hibernate.format_sql=true
#Configures the naming strategy that is used when Hibernate creates
#new database objects and schema elements
hibernate.hbm2ddl.auto=update
#If the value of this property is true, Hibernate writes all SQL
#statements to the console.
## DEPRECATED IN 5.0 ##hibernate.ejb.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy
hibernate.implicit_naming_strategy=default
#If the value of this property is true, Hibernate will use prettyprint
#when it writes SQL to the console.
hibernate.show_sql=false
#configure hibernate to use UTC
hibernate.jdbc.time_zone=UTC


##############  File Upload Configuration       ##############

#multipart.maxFileSize: 128KB
#multipart.maxRequestSize: 128KB
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
image.aspect_ratio=0.75

#spring.data.rest.detection-strategy=annotated

##############  Security Configuration       ##############
#Comment this to re-enable security
#also uncomment imported security.xml in applicationContext.xml
#also add oxi.security to component scanning in Application.java and uncomment @EnableWebSecurity

security.basic.enabled=false
management.security.enabled=false


################### JavaMail Configuration ##########################
support.email=no-reply@oxisalechannel.com
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.protocol=smtps

#spring.mail.username=devenb@oxisalechannel.com
#spring.mail.password=srutfobyjqwmppcl

spring.mail.username=support@oxisalechannel.com
spring.mail.password=skrvrkdigdrxumbn

spring.mail.properties.mail.transport.protocol=smtps
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.starttls.enable=true
spring.mail.properties.mail.smtps.timeout=8000


################# Elasticsearch Configuration #######################
#note 
#  port 9200 exposes elasticsearch rest api
#  port 9300 expostes elasticsearch's cluster node
spring.data.elasticsearch.cluster-nodes=${ES_HOSTNAME}:9200

# Elasticsearch cluster name.
#spring.data.elasticsearch.cluster-name=elasticsearch
spring.data.elasticsearch.cluster-name=${ES_CLUSTER_NAME}

## Additional properties used to configure the client.
#spring.data.elasticsearch.properties.*= 

# Whether to enable Elasticsearch repositories.
spring.data.elasticsearch.repositories.enabled=true

# confilicting beran name with elasticsearchClient
#spring.main.allow-bean-definition-overriding=true