#


#Username and Password must be URL-encoded when values containe reserved characters such as ':','%','@', or ','
mongo.host=localhost
mongo.port=27017
mongo.database=test2
mongo.username=oxi
mongo.password=feisthmiki#10

mongo.connectionsPerHost=8
mongo.threadsAllowedToBlockForConnectionMultiplier=4
mongo.connectTimeout=1000
mongo.maxWaitTime=1500
#mongo.autoConnectRetry=true
mongo.socketKeepAlive=true
mongo.socketTimeout=1500
#mongo.slaveOk=true
mongo.writeConcern=FSYNC_SAFE